### PR TITLE
Issue #360: Updating examples to use simplified accounts

### PR DESCRIPTION
**Pull request by ElliotFriend**
I've used `sed` to go through all the mdx files in the `content/`
directory and changed the Go code samples to use the new, simplified syntax.

I'd love some feedback, as I've never used Go. I'm not sure if there are
other places to look for these code samples in the repo, as well.

Signed-off-by: Elliot J. Voris <elliot@voris.me>

### CODE REVIEW

**Comment by ElliotFriend** [comment]
Hold that thought... I've done something strange to some whitespace in this one. Let me fix that.

**Comment by ElliotFriend** [comment]
Maybe I didn't mess up the whitespace like I thought... Are there some pre-commit scripts that run in this repo? I saw "Fixing up `filename.mdx`" display before I could enter my commit message. Are there some automatic formatting rules that are applied during the commit process?

**Comment by Shaptic** [comment]
Thank you for your pull request, @ElliotFriend! Though your account changes are fantastic, there do seem to be a *lot* of extraneous changes, mostly related to whitespace JS linting. I don't think there are any commit hooks, so I'm not sure where the "fixing up" comes from. Can you remove the non-account changes?

**Comment by ElliotFriend** [comment]
Yeah, I thought it was strange, but if it was the way you all liked it done, I wasn't gonna complain Hehe

I'll get that nonsense stripped out and re-push. Thanks!

**Comment by ElliotFriend** [comment]
Looks like [this line](https://github.com/stellar/new-docs/blob/687f0168740182a3f4a2cfa34dde722da104c482/package.json#L17) in `package.json` runs a pre-commit task. Looks like the call to `pretty-quick --staged` only runs the linting on the changed files.

**Review by Shaptic — APPROVED** [review]
Ah, much better! Thank you for this change :+1:

**Pull request merged**
