### PR TITLE
Add SEP-31 and refactor for multiple SEPs for anchors

### PR DESCRIPTION
**Pull request by JakeUrban**

### CODE REVIEW

**Comment by JakeUrban** [comment]
@rice2000 work in progress, will ping you to review soon!

**Comment by rice2000** [comment]
This is looking great!

**Comment by JakeUrban** [comment]
@rice2000 the preview doesn't seem to be updating after the first commit, but I'm largely done with the SEP-31 changes. I can also improve the 'Where to Start` section and clean up the SEP-24 verbage.

**Review by rice2000 — APPROVED** [review]
This is great!  Nice work.  I think we should merge this now, and I can do a copy edit pass as a separate PR.

**Pull request merged**
