### PR TITLE
result code updates

### PR DESCRIPTION
**Pull request by kylemccollom**

### CODE REVIEW

**Comment by kylemccollom** [comment]
this is not ready to be merged yet - should be done by the end of the week. it looks like previews are broken right now.

**Comment by vcarl** [comment]
@kylemccollom I marked this as a draft, when it's ready to go hit the "Ready for review" button. We can review it as you push changes

**Comment by rice2000** [comment]
@tyvdh Is this ready to merge?  It's still marked as a draft.

**Comment by tyvdh** [comment]
Yep. Good to go as far as I know.

**Pull request merged**
