### PR TITLE
In connect to anchors section:  - Removed any mention to stellar-anchor-server.herokuapp.com since it is not used anymore and available for takeover.

### PR DESCRIPTION
**Pull request by C0x41lch0x41**
HackerOne report: 1649820

### CODE REVIEW

**Comment by C0x41lch0x41** [comment]
@rice2000 @JakeUrban please take a look thanks!

**Review by JakeUrban — APPROVED** [review]
We could use the testanchor.stellar.org domain, but if we choose not to, this LGTM.

**Comment by C0x41lch0x41** [comment]
Ah did not know we had this domain. That may be better. Let me push an update.

**Review by rice2000 — APPROVED** [review]
Nice!

**Pull request merged**
