### PR TITLE
Make expansion timing more consistent

### PR DESCRIPTION
**Pull request by vcarl**
With how we we doing animated expansions before, the timing varied because the exact height wasn't known in advance. By providing information about the height to the component in question, it will always run for the length of time specified.

### CODE REVIEW

**Comment by jeesunikim** [comment]
I'm seeing a glitch when expanding side navigation on /docs locally. I attached a video in asana [ticket](https://app.asana.com/0/1130719348309291/1175224232695565). Does this happen to you too, @piyalbasu? I wonder if it's just me.

**Comment by vcarl** [comment]
I'm seeing it too, definitely something up. We pretty consistently have some weird issues with font loading, I'm not sure why. I assume it has something to do with `GlobalStyles` somehow refreshing, but afaik styled-components/gatsby has been set up correctly 🤔

**Comment by jeesunikim** [comment]
I wonder why it's more noticeable now than it was before

**Comment by vcarl** [comment]
I noticed this doesn't account for when the expanded section changes height after mounting, like when an API reference sub-section enters the view. Gonna have to rework it
Screen Shot 2020-05-26 at 11 47 29 AM
Screen Shot 2020-05-26 at 11 47 21 AM

**Pull request merged**
